### ISSUE TITLE
Test that the issues and projects pages are visible to collaborators.

### ISSUE THREAD

**Issue by mbcann01** [mbcann01/waiver_evaluation#2]

**Comment by mbcann01** [comment]
Hey @rudy-perez,

Are you able to see/edit/comment on this issue?

Are you able to see the [project overview](https://github.com/brad-cannell/waiver_evaluation/projects/1)?

**Comment by rudy-perez** [comment]
Hi, Brad. Yes, I am.

**Comment by mbcann01** [comment]
@rudy-perez Are you able to close this issue out? If so, please go ahead and do it (just for the practice).
